spring.application.name=event-driven-banking-system
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username=postgres
spring.datasource.password=Poorva@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#axon server
# Disable Axon Server for now
axon.axonserver.enabled=false
axon.eventhandling.processors.default.mode=subscribing
